#### Filtering

In [37]:
# Menampilkan Filter transaksi bernilai tinggi

high_value_transaction = df_analysis[df_analysis['Total Spent'] >= 20]
high_value_transaction.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Year,Month,Month Name,Day Name,Spending Category
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,Takeaway,2023-03-31,2023,3,March,Friday,High
9,TXN_2064365,Sandwich,5,4.0,20.0,Digital Wallet,In-store,2023-12-31,2023,12,December,Sunday,High
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07,2023,11,November,Tuesday,Very High
20,TXN_3522028,Smoothie,5,4.0,20.0,Cash,In-store,2023-04-04,2023,4,April,Tuesday,High
24,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03,2023,6,June,Saturday,High
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,In-store,2023-03-11,2023,3,March,Saturday,High
51,TXN_6342161,Salad,5,5.0,25.0,Credit Card,Takeaway,2023-01-08,2023,1,January,Sunday,Very High
52,TXN_8914892,Salad,5,5.0,25.0,Digital Wallet,Takeaway,2023-03-15,2023,3,March,Wednesday,Very High
54,TXN_8614868,Smoothie,5,4.0,20.0,Digital Wallet,Takeaway,2023-12-05,2023,12,December,Tuesday,High
96,TXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10,2023,6,June,Saturday,Very High

In [38]:
# Menampilkan Filter produk dengan harga tinggi

premium_product_transaction = df_analysis[df_analysis['Price Per Unit'] >= 4.0]
premium_product_transaction.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Year,Month,Month Name,Day Name,Spending Category
3,TXN_7034554,Salad,2,5.0,10.0,Digital Wallet,In-store,2023-04-27,2023,4,April,Thursday,Medium
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,Takeaway,2023-03-31,2023,3,March,Friday,High
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,In-store,2023-10-28,2023,10,October,Saturday,High
9,TXN_2064365,Sandwich,5,4.0,20.0,Digital Wallet,In-store,2023-12-31,2023,12,December,Sunday,High
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07,2023,11,November,Tuesday,Very High
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03,2023,5,May,Wednesday,Medium
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15,2023,11,November,Wednesday,High
16,TXN_3765707,Sandwich,1,4.0,4.0,Digital Wallet,In-store,2023-06-10,2023,6,June,Saturday,Low
20,TXN_3522028,Smoothie,5,4.0,20.0,Cash,In-store,2023-04-04,2023,4,April,Tuesday,High
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30,2023,3,March,Thursday,High

In [39]:
# Menampilkan Filter transaksi berdasarkan lokasi

instore_transaction = df_analysis[df_analysis['Location'] == 'In-store']
instore_transaction.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Year,Month,Month Name,Day Name,Spending Category
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,2023,5,May,Tuesday,High
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,2023,7,July,Wednesday,Low
3,TXN_7034554,Salad,2,5.0,10.0,Digital Wallet,In-store,2023-04-27,2023,4,April,Thursday,Medium
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023,6,June,Sunday,Low
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,In-store,2023-10-28,2023,10,October,Saturday,High

Filtering digunakan untuk mengambil data berdasarkan kondisi tertentu. 

Pada bagian ini, filtering dilakukan untuk melihat transaksi bernilai tinggi, produk dengan harga tinggi, serta transaksi berdasarkan lokasi. Hal ini berguna untuk memahami pola transaksi yang paling berkontribusi terhadap revenue.

#### Sorting

In [40]:
# Mengurutkan transaksi berdasarkan Total Spent tertinggi
top_transactions = df_analysis.sort_values(by='Total Spent', ascending=False)

top_transactions.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Year,Month,Month Name,Day Name,Spending Category
4561,TXN_7442492,Salad,5,5.0,25.0,Credit Card,Takeaway,2023-07-23,2023,7,July,Sunday,Very High
6373,TXN_3212317,Salad,5,5.0,25.0,Cash,Takeaway,2023-05-25,2023,5,May,Thursday,Very High
6844,TXN_1759314,Salad,5,5.0,25.0,Cash,In-store,2023-08-23,2023,8,August,Wednesday,Very High
557,TXN_1183995,Salad,5,5.0,25.0,Digital Wallet,Takeaway,2023-03-28,2023,3,March,Tuesday,Very High
4639,TXN_6369590,Salad,5,5.0,25.0,Digital Wallet,Takeaway,2023-10-26,2023,10,October,Thursday,Very High
7570,TXN_4155770,Salad,5,5.0,25.0,Cash,In-store,2023-09-20,2023,9,September,Wednesday,Very High
1055,TXN_1413304,Salad,5,5.0,25.0,Cash,Takeaway,2023-03-17,2023,3,March,Friday,Very High
5175,TXN_4417257,Salad,5,5.0,25.0,Digital Wallet,Takeaway,2023-05-06,2023,5,May,Saturday,Very High
4630,TXN_6536418,Salad,5,5.0,25.0,Credit Card,In-store,2023-02-11,2023,2,February,Saturday,Very High
570,TXN_2392263,Salad,5,5.0,25.0,Digital Wallet,Takeaway,2023-02-08,2023,2,February,Wednesday,Very High

Sorting digunakan untuk mengurutkan data berdasarkan Total Spent tertinggi. 
Dengan cara ini, transaksi dengan nilai pembelian terbesar dapat dianalisis lebih lanjut.

#### Groupby

Groupby digunakan untuk mengelompokkan data berdasarkan kategori tertentu. 

Pada analisis ini, groupby digunakan untuk melihat performa penjualan berdasarkan Item, Payment Method, dan Location. Hasil agregasi menunjukkan total quantity, total revenue, rata-rata spending, dan jumlah transaksi.

In [41]:
# Revenue per item

item_summary = df_analysis.groupby('Item').agg(
    Total_Quantity=('Quantity', 'sum'),
    Total_Revenue=('Total Spent', 'sum'),
    Average_Spending=('Total Spent', 'mean'),
    Total_Transaction=('Transaction ID', 'count')
).sort_values(by='Total_Revenue', ascending=False)

item_summary

          Total_Quantity  Total_Revenue  Average_Spending  Total_Transaction
Item
Salad               3644        18220.0         15.008237               1214
Sandwich            3612        14448.0         12.182125               1186
Smoothie            3518        14072.0         12.268527               1147
Juice               3689        11067.0          8.946645               1237
Cake                3647        10941.0          9.125104               1199
Coffee              3766         7532.0          6.069299               1241
Tea                 3441         5161.5          4.523663               1141
Cookie              3427         3427.0          2.982594               1149

In [42]:
# Revenue per payment method

payment_summary = df_analysis.groupby('Payment Method').agg(
    Total_Revenue=('Total Spent', 'sum'),
    Total_Transaction=('Transaction ID', 'count'),
    Average_Spending=('Total Spent', 'mean')
).sort_values(by='Total_Revenue', ascending=False)

payment_summary

                Total_Revenue  Total_Transaction  Average_Spending
Payment Method
Credit Card           28573.5               3201          8.926429
Cash                  28296.5               3163          8.946095
Digital Wallet        27998.5               3150          8.888413

In [43]:
# Revenue per location

location_summary = df_analysis.groupby('Location').agg(
    Total_Revenue=('Total Spent', 'sum'),
    Total_Transaction=('Transaction ID', 'count'),
    Average_Spending=('Total Spent', 'mean')
).sort_values(by='Total_Revenue', ascending=False)

location_summary

          Total_Revenue  Total_Transaction  Average_Spending
Location
In-store        42936.0               4750          9.039158
Takeaway        41932.5               4764          8.801952

#### Analisis Tren Bulanan

Analisis tren bulanan dilakukan untuk melihat perubahan revenue dari Januari sampai Desember. 

Hasil ini dapat membantu mengetahui bulan dengan performa penjualan tertinggi dan terendah.

In [44]:
month_order = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]

monthly_revenue = df_analysis.groupby('Month Name')['Total Spent'].sum().reindex(month_order)

monthly_revenue

Month Name
January      7254.0
February     6644.0
March        7216.0
April        7179.0
May          6932.5
June         7353.0
July         6877.5
August       7092.5
September    6871.0
October      7314.0
November     6967.0
December     7168.0
Name: Total Spent, dtype: float64